version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80      

  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: MY_DATABASE
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
    volumes:
      - ./MySQL.txt:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "9906:3306"

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: MY_DATABASE
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
    volumes:
      - ./MariaDB.txt:/docker-entrypoint-initdb.d/init.sql
    ports:
        - "3307:3306"
        
  phpmyadminMaria:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8090:80'
    restart: always
    environment:
        PMA_HOST: mariadb
    depends_on:
        - mariadb

  phpmyadminMySQL:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8091:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
      - db